### ISSUE TITLE
feat(autocomplete): Configuration for opening autocomplete upwards from input

### ISSUE THREAD

**Issue by terohe** [mbenford/ngTagsInput#137]
It would be great if it could be controlled to which direction the autocomplete opens. Currently the autocomplete seems to open always downwards from the tag input. The best would be if the autocomplete could open the autocomplete upwards if it does not have room downwards. But some additional configuration would also serve the purpose.

Use case: The tag input is at the bottom of the page and opening autocomplete downwards just makes the page longer.

**Comment by vladjerca** [comment]
I have a really simple solution:

```scss
@mixin transform($transforms) {
	   -moz-transform: $transforms;
	     -o-transform: $transforms;
	    -ms-transform: $transforms;
	-webkit-transform: $transforms;
          transform: $transforms;
}
// rotate
@mixin rotate ($deg) {
  @include transform(rotate(#{$deg}deg));
}

.reverse-autocomplete {
        .autocomplete {
            bottom: 100%;
        }
        .suggestion-list {
            @include rotate(180);
        }
        .suggestion-item {
            @include rotate(-180);
        }
    }
```

```html
<tags-input>
        <auto-complete class="reverse-autocomplete"></auto-complete>
</tags-input>
```

ONE DOWNSIDE:

When you navigate through them using the arrows, they go the other way around. So a possible solution would be to include this CSS in ngTagsInput base and when flagged, also reverse the navigation direction :).
