### ISSUE TITLE
How to forbidden the input?

### ISSUE THREAD

**Issue by luoluoying** [mbenford/ngTagsInput#758]
I just want to show the Tags  what I defined in my controller . I don't want user to input anything in it ? I'm not sure has the config, but I can't find any config to forbidden. any one know how to do?
Thanks~!

**Comment by dclangan** [comment]
I discovered that adding ng-disabled to the tags-input does what you are looking for. In addition, I added some css to hide .input and .remove-button.
```css
tags-input[disabled] .tags .input, 
tags-input[disabled] .tags .tag-item .remove-button {
    display: none;
} 
```
